strs = "wellspacewelllspacehousespaceintospacethisspaceyouspaceonlyspacebyspacefirstspacefollowspacearoundspacepresentspaceofspacebecomespacewhospacemanyspacefindspacefeelspacecoursespacegbackspaceagainspaceintospacebbackspacepeoplespacebecausespacepersonspaceincreasespacepublicspacehousespaceorspaceaspaceaboutspaceearlyspacethinkspacewhs"

output_string = strs.replace("space", " ")

print(output_string)
